services:
  test-backend-7:
    build:
      context: .
      target: production
    image: test-backend-7
    container_name: test-backend-7
    depends_on:
      - test-backend-7-postgres
    environment:
      APPINSIGHTS_CLOUDROLE: test-backend-7-local
      APPINSIGHTS_CONNECTIONSTRING: ${APPINSIGHTS_CONNECTIONSTRING}

  test-backend-7-postgres:
    image: postgres:11.4-alpine
    environment:
      POSTGRES_DB: test-backend-7
      POSTGRES_PASSWORD: ppp
      POSTGRES_USERNAME: postgres
